version: 2.1
orbs:
  jq: circleci/jq@1.9.0 # needed to install tools from docker orb
  docker: circleci/docker@0.5.0
jobs:
  build:
    parallelism: 1
    docker:
      - image: verybigthings/elixir:1.9
        environment:
          MIX_ENV: "test"
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vbt_test
    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION}}-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION}}-skafolder-tester-cache-{{ .Branch }}-{{ checksum "test_projects/skafolder_tester/mix.lock" }}'
      - run:
          name: "Get deps"
          command: mix deps.get
      - run:
          name: "Compile project"
          command: mix compile --warnings-as-errors
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION}}-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}'
          paths:
            - deps
            - _build
      - jq/install
      - docker/install-dockerize
      - run:
          name: "Run linter checks"
          command: mix credo --strict
      - run:
          name: "Check code format"
          command: mix format --check-formatted
      - restore_cache:
          keys:
            - '{{ .Environment.CACHE_VERSION}}-dialyzer-cache-{{ .Branch }}-{{ checksum "mix.lock" }}'
            - '{{ .Environment.CACHE_VERSION}}-dialyzer-cache-{{ .Branch }}-'
            - '{{ .Environment.CACHE_VERSION}}-dialyzer-cache-'
      - run:
          name: "Restore cached dialyzer files"
          command: "mkdir -p plts && ls plts | xargs -I % cp plts/% _build/$MIX_ENV/"
      - run:
          name: "Build dialyzer plt"
          command: mix dialyzer --plt
      - run:
          name: "Prepare dialyzer files to cache"
          command: "mkdir -p plts && ls _build/$MIX_ENV | grep dialyxir | xargs -I % cp _build/$MIX_ENV/% -t plts"
      - save_cache:
          paths:
            - plts
            - ~/.mix
          key: '{{ .Environment.CACHE_VERSION}}-dialyzer-cache-{{ .Branch }}-{{ checksum "mix.lock" }}'
      - run:
          name: "Run Dialyzer checks"
          command: mix dialyzer --halt-exit-status
      - run:
          name: "Run tests"
          command: mix test
      - save_cache:
          key: '{{ .Environment.CACHE_VERSION}}-skafolder-tester-cache-{{ .Branch }}-{{ checksum "test_projects/skafolder_tester/mix.lock" }}'
          paths:
            - test_projects/skafolder_tester/deps
            - test_projects/skafolder_tester/_build
  update_docs:
    docker:
      - image: verybigthings/elixir:1.9
    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION}}-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}'
      - restore_cache:
          key: '{{ .Environment.CACHE_VERSION}}-skafolder-tester-cache-{{ .Branch }}-{{ checksum "test_projects/skafolder_tester/mix.lock" }}'
      - run:
          name: "Install awscli"
          command: apt-get update && apt-get install -y make awscli
      - run:
          name: "Get deps"
          command: mix deps.get
      - run:
          name: "Generate docs"
          command: mix docs
      - run:
          name: "Update docs"
          command: aws s3 sync --acl public-read --delete --region us-east-1 ./doc/ s3://vbt-common-docs/
workflows:
  version: 2
  build_feature:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /^WIP\/.*/
      - update_docs:
          filters:
            branches:
              only:
                - master
