name: "Deploy"

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    env:
      CACHE_VERSION: v1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2.8
          elixir-version: 1.10.2

      - name: Restore cached deps
        uses: actions/cache@v1
        with:
          path: deps
          key: deps-${{ env.CACHE_VERSION }}-${{ github.ref }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            deps-${{ env.CACHE_VERSION }}-${{ github.ref }}-
            deps-${{ env.CACHE_VERSION }}-

      - name: Restore cached build
        uses: actions/cache@v1
        with:
          path: _build
          key: build-${{ env.CACHE_VERSION }}-${{ github.ref }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            build-${{ env.CACHE_VERSION }}-${{ github.ref }}-
            build-${{ env.CACHE_VERSION }}-

      - name: Fetch deps
        run: mix deps.get

      - name: Build docs
        run: mix docs

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Release docs"
        run: aws s3 sync --acl public-read --delete --region us-east-1 ./doc/ s3://vbt-common-docs/

  vbt_new:
    name: Deploy vbt_new
    runs-on: ubuntu-latest
    env:
      CACHE_VERSION: v1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2.8
          elixir-version: 1.10.2

      - name: Restore cached deps
        uses: actions/cache@v1
        with:
          path: vbt_new/deps
          key: vbt_new_deps-${{ env.CACHE_VERSION }}-${{ github.ref }}-${{ hashFiles(format('{0}{1}', github.workspace, '/vbt_new/mix.lock')) }}
          restore-keys: |
            vbt_new_deps-${{ env.CACHE_VERSION }}-${{ github.ref }}-
            vbt_new_deps-${{ env.CACHE_VERSION }}-

      - name: Restore cached build
        uses: actions/cache@v1
        with:
          path: vbt_new/_build
          key: vbt_new_build-${{ env.CACHE_VERSION }}-${{ github.ref }}-${{ hashFiles(format('{0}{1}', github.workspace, '/vbt_new/mix.lock')) }}
          restore-keys: |
            vbt_new_build-${{ env.CACHE_VERSION }}-${{ github.ref }}-
            vbt_new_build-${{ env.CACHE_VERSION }}-

      - name: Fetch deps
        run: cd vbt_new && mix deps.get

      - name: Build archive
        run: cd vbt_new && mix archive.build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy archive
        run: aws s3 cp --acl public-read --region us-east-1 ./vbt_new/vbt_new-0.1.0.ez s3://vbt-common-docs/vbt_new.ez
